//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.Files.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FilesCommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FilesCommonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.Files.Resources.FilesCommonResource", typeof(FilesCommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me.
        /// </summary>
        public static string Author_Me {
            get {
                return ResourceManager.GetString("Author_Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete from the list.
        /// </summary>
        public static string ButtonDeleteFromShare {
            get {
                return ResourceManager.GetString("ButtonDeleteFromShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string ButtonDownload {
            get {
                return ResourceManager.GetString("ButtonDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is being edited.
        /// </summary>
        public static string ButtonEditing {
            get {
                return ResourceManager.GetString("ButtonEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to the folder.
        /// </summary>
        public static string ButtonPreviewBack {
            get {
                return ResourceManager.GetString("ButtonPreviewBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update document.
        /// </summary>
        public static string ButtonUploadNewVersions {
            get {
                return ResourceManager.GetString("ButtonUploadNewVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date:.
        /// </summary>
        public static string CreatingDate {
            get {
                return ResourceManager.GetString("CreatingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Time.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Name:.
        /// </summary>
        public static string DocumentName {
            get {
                return ResourceManager.GetString("DocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad request..
        /// </summary>
        public static string ErrorMassage_BadRequest {
            get {
                return ResourceManager.GetString("ErrorMassage_BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to create folders in the Trash.
        /// </summary>
        public static string ErrorMassage_CreateNewFolderInTrash {
            get {
                return ResourceManager.GetString("ErrorMassage_CreateNewFolderInTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the file to upload is different from the source file.
        /// </summary>
        public static string ErrorMassage_DifferentName {
            get {
                return ResourceManager.GetString("ErrorMassage_DifferentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty file.
        /// </summary>
        public static string ErrorMassage_EmptyFile {
            get {
                return ResourceManager.GetString("ErrorMassage_EmptyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum file size is exceeded .
        /// </summary>
        public static string ErrorMassage_ExceededMaximumFileSize {
            get {
                return ResourceManager.GetString("ErrorMassage_ExceededMaximumFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required file was not found.
        /// </summary>
        public static string ErrorMassage_FileNotFound {
            get {
                return ResourceManager.GetString("ErrorMassage_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required folder was not found.
        /// </summary>
        public static string ErrorMassage_FolderNotFound {
            get {
                return ResourceManager.GetString("ErrorMassage_FolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder with the same name already exists. Rename the folder and try again..
        /// </summary>
        public static string ErrorMassage_MoveFolder {
            get {
                return ResourceManager.GetString("ErrorMassage_MoveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this file format isn&apos;t supported.
        /// </summary>
        public static string ErrorMassage_NotSupportedFormat {
            get {
                return ResourceManager.GetString("ErrorMassage_NotSupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough permission to perform the operation.
        /// </summary>
        public static string ErrorMassage_SecurityException {
            get {
                return ResourceManager.GetString("ErrorMassage_SecurityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough permission to create.
        /// </summary>
        public static string ErrorMassage_SecurityException_Create {
            get {
                return ResourceManager.GetString("ErrorMassage_SecurityException_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete the file because it is opened for editing.
        /// </summary>
        public static string ErrorMassage_SecurityException_DeleteEditingFile {
            get {
                return ResourceManager.GetString("ErrorMassage_SecurityException_DeleteEditingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete the folder because one of the files is opened for editing.
        /// </summary>
        public static string ErrorMassage_SecurityException_DeleteEditingFolder {
            get {
                return ResourceManager.GetString("ErrorMassage_SecurityException_DeleteEditingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough permission to delete the file.
        /// </summary>
        public static string ErrorMassage_SecurityException_DeleteFile {
            get {
                return ResourceManager.GetString("ErrorMassage_SecurityException_DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough permission to delete the folder.
        /// </summary>
        public static string ErrorMassage_SecurityException_DeleteFolder {
            get {
                return ResourceManager.GetString("ErrorMassage_SecurityException_DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have enough permissions to edit the file.
        /// </summary>
        public static string ErrorMassage_SecurityException_EditFile {
            get {
                return ResourceManager.GetString("ErrorMassage_SecurityException_EditFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough permission to view the file.
        /// </summary>
        public static string ErrorMassage_SecurityException_ReadFile {
            get {
                return ResourceManager.GetString("ErrorMassage_SecurityException_ReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough permission to view the folder content.
        /// </summary>
        public static string ErrorMassage_SecurityException_ReadFolder {
            get {
                return ResourceManager.GetString("ErrorMassage_SecurityException_ReadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough permission to rename the file.
        /// </summary>
        public static string ErrorMassage_SecurityException_RenameFile {
            get {
                return ResourceManager.GetString("ErrorMassage_SecurityException_RenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough permission to rename the folder.
        /// </summary>
        public static string ErrorMassage_SecurityException_RenameFolder {
            get {
                return ResourceManager.GetString("ErrorMassage_SecurityException_RenameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update the file because it&apos;s opened for editing.
        /// </summary>
        public static string ErrorMassage_SecurityException_UpdateEditingFile {
            get {
                return ResourceManager.GetString("ErrorMassage_SecurityException_UpdateEditingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough permission to view the folder content.
        /// </summary>
        public static string ErrorMassage_SecurityException_ViewFolder {
            get {
                return ResourceManager.GetString("ErrorMassage_SecurityException_ViewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot update a file which is opened for editing.
        /// </summary>
        public static string ErrorMassage_UpdateEditingFile {
            get {
                return ResourceManager.GetString("ErrorMassage_UpdateEditingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to preview the elements in the Trash.
        /// </summary>
        public static string ErrorMassage_ViewTrashItem {
            get {
                return ResourceManager.GetString("ErrorMassage_ViewTrashItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload with Flash.
        /// </summary>
        public static string FlashUploader {
            get {
                return ResourceManager.GetString("FlashUploader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash uploader version....
        /// </summary>
        public static string FlashUploaderDescription {
            get {
                return ResourceManager.GetString("FlashUploaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload with Html.
        /// </summary>
        public static string HtmlUploader {
            get {
                return ResourceManager.GetString("HtmlUploader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from Box.Net.
        /// </summary>
        public static string ImportFromBoxNet {
            get {
                return ResourceManager.GetString("ImportFromBoxNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from Google Docs.
        /// </summary>
        public static string ImportFromGoogle {
            get {
                return ResourceManager.GetString("ImportFromGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from Zoho.
        /// </summary>
        public static string ImportFromZoho {
            get {
                return ResourceManager.GetString("ImportFromZoho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new.
        /// </summary>
        public static string IsNew {
            get {
                return ResourceManager.GetString("IsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string MakeCurrent {
            get {
                return ResourceManager.GetString("MakeCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group management.
        /// </summary>
        public static string ManagmentGroup {
            get {
                return ResourceManager.GetString("ManagmentGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing has been found.
        /// </summary>
        public static string NothingFound {
            get {
                return ResourceManager.GetString("NothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview documents.
        /// </summary>
        public static string PreviewHeader {
            get {
                return ResourceManager.GetString("PreviewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create, edit, save and share documents directly on your portal. Import docs base from Google Docs, Zoho, Box.net..
        /// </summary>
        public static string ProductDescription {
            get {
                return ResourceManager.GetString("ProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select.
        /// </summary>
        public static string SelectRight {
            get {
                return ResourceManager.GetString("SelectRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Results.
        /// </summary>
        public static string ShowAllResults {
            get {
                return ResourceManager.GetString("ShowAllResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned to Me.
        /// </summary>
        public static string SignedForMe {
            get {
                return ResourceManager.GetString("SignedForMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips and Tricks.
        /// </summary>
        public static string TipsAndTricks {
            get {
                return ResourceManager.GetString("TipsAndTricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show operations.
        /// </summary>
        public static string TitleActionPanel {
            get {
                return ResourceManager.GetString("TitleActionPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string TitleCreated {
            get {
                return ResourceManager.GetString("TitleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is currently being edited.
        /// </summary>
        public static string TitleEditingFile {
            get {
                return ResourceManager.GetString("TitleEditingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string TitleFiles {
            get {
                return ResourceManager.GetString("TitleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string TitleFolderUp {
            get {
                return ResourceManager.GetString("TitleFolderUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kb.
        /// </summary>
        public static string TitleKb {
            get {
                return ResourceManager.GetString("TitleKb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string TitleModified {
            get {
                return ResourceManager.GetString("TitleModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string TitleOwner {
            get {
                return ResourceManager.GetString("TitleOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string TitlePage {
            get {
                return ResourceManager.GetString("TitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string TitleRemoved {
            get {
                return ResourceManager.GetString("TitleRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete version.
        /// </summary>
        public static string TitleRemoveVersion {
            get {
                return ResourceManager.GetString("TitleRemoveVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string TitleSelectFile {
            get {
                return ResourceManager.GetString("TitleSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to document is allowed.
        /// </summary>
        public static string TitleShareFile {
            get {
                return ResourceManager.GetString("TitleShareFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subfolders.
        /// </summary>
        public static string TitleSubfolders {
            get {
                return ResourceManager.GetString("TitleSubfolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded.
        /// </summary>
        public static string TitleUploaded {
            get {
                return ResourceManager.GetString("TitleUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous versions.
        /// </summary>
        public static string TitleVersions {
            get {
                return ResourceManager.GetString("TitleVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total found.
        /// </summary>
        public static string TotalFound {
            get {
                return ResourceManager.GetString("TotalFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ver..
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver.№.
        /// </summary>
        public static string VersionNum {
            get {
                return ResourceManager.GetString("VersionNum", resourceCulture);
            }
        }
    }
}
