//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.Files.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FilesUCResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FilesUCResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.Files.Resources.FilesUCResource", typeof(FilesUCResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Only.
        /// </summary>
        public static string AceStatusEnum_Read {
            get {
                return ResourceManager.GetString("AceStatusEnum_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Access.
        /// </summary>
        public static string AceStatusEnum_ReadWrite {
            get {
                return ResourceManager.GetString("AceStatusEnum_ReadWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny Access.
        /// </summary>
        public static string AceStatusEnum_Restrict {
            get {
                return ResourceManager.GetString("AceStatusEnum_Restrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrators.
        /// </summary>
        public static string Administrators {
            get {
                return ResourceManager.GetString("Administrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Group.
        /// </summary>
        public static string ButtonAddGroup {
            get {
                return ResourceManager.GetString("ButtonAddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string ButtonAddUser {
            get {
                return ResourceManager.GetString("ButtonAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filter.
        /// </summary>
        public static string ButtonClearFilter {
            get {
                return ResourceManager.GetString("ButtonClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string ButtonCopyTo {
            get {
                return ResourceManager.GetString("ButtonCopyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Folder.
        /// </summary>
        public static string ButtonCreateFolder {
            get {
                return ResourceManager.GetString("ButtonCreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Group.
        /// </summary>
        public static string ButtonCreateGroup {
            get {
                return ResourceManager.GetString("ButtonCreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Presentation.
        /// </summary>
        public static string ButtonCreatePresentation {
            get {
                return ResourceManager.GetString("ButtonCreatePresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Spreadsheet.
        /// </summary>
        public static string ButtonCreateSpreadsheet {
            get {
                return ResourceManager.GetString("ButtonCreateSpreadsheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Document.
        /// </summary>
        public static string ButtonCreateText {
            get {
                return ResourceManager.GetString("ButtonCreateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string ButtonDownload {
            get {
                return ResourceManager.GetString("ButtonDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit in OpenOffice.
        /// </summary>
        public static string ButtonEditOO {
            get {
                return ResourceManager.GetString("ButtonEditOO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send by Email.
        /// </summary>
        public static string ButtonEmailLink {
            get {
                return ResourceManager.GetString("ButtonEmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add group.
        /// </summary>
        public static string ButtonEmptyGroup {
            get {
                return ResourceManager.GetString("ButtonEmptyGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Trash.
        /// </summary>
        public static string ButtonEmptyTrash {
            get {
                return ResourceManager.GetString("ButtonEmptyTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Current Folder.
        /// </summary>
        public static string ButtonFavoritesAdd {
            get {
                return ResourceManager.GetString("ButtonFavoritesAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string ButtonFilterDocument {
            get {
                return ResourceManager.GetString("ButtonFilterDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string ButtonFilterFile {
            get {
                return ResourceManager.GetString("ButtonFilterFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string ButtonFilterFolder {
            get {
                return ResourceManager.GetString("ButtonFilterFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string ButtonFilterPicture {
            get {
                return ResourceManager.GetString("ButtonFilterPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentations.
        /// </summary>
        public static string ButtonFilterPresentation {
            get {
                return ResourceManager.GetString("ButtonFilterPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spreadsheets.
        /// </summary>
        public static string ButtonFilterSpreadsheet {
            get {
                return ResourceManager.GetString("ButtonFilterSpreadsheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Size.
        /// </summary>
        public static string ButtonFullScale {
            get {
                return ResourceManager.GetString("ButtonFullScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string ButtonGallery {
            get {
                return ResourceManager.GetString("ButtonGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get link.
        /// </summary>
        public static string ButtonGetLink {
            get {
                return ResourceManager.GetString("ButtonGetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string ButtonImport {
            get {
                return ResourceManager.GetString("ButtonImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string ButtonList {
            get {
                return ResourceManager.GetString("ButtonList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string ButtonMinimize {
            get {
                return ResourceManager.GetString("ButtonMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to.
        /// </summary>
        public static string ButtonMoveTo {
            get {
                return ResourceManager.GetString("ButtonMoveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Image.
        /// </summary>
        public static string ButtonNextImg {
            get {
                return ResourceManager.GetString("ButtonNextImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Actions.
        /// </summary>
        public static string ButtonOtherAction {
            get {
                return ResourceManager.GetString("ButtonOtherAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Image.
        /// </summary>
        public static string ButtonPrevImg {
            get {
                return ResourceManager.GetString("ButtonPrevImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string ButtonRename {
            get {
                return ResourceManager.GetString("ButtonRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string ButtonRestore {
            get {
                return ResourceManager.GetString("ButtonRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite.
        /// </summary>
        public static string ButtonRewrite {
            get {
                return ResourceManager.GetString("ButtonRewrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Counterclockwise.
        /// </summary>
        public static string ButtonRotateLeft {
            get {
                return ResourceManager.GetString("ButtonRotateLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Clockwise.
        /// </summary>
        public static string ButtonRotateRight {
            get {
                return ResourceManager.GetString("ButtonRotateRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string ButtonSelectFiles {
            get {
                return ResourceManager.GetString("ButtonSelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select group.
        /// </summary>
        public static string ButtonSelectGroup {
            get {
                return ResourceManager.GetString("ButtonSelectGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        public static string ButtonShare {
            get {
                return ResourceManager.GetString("ButtonShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Settings.
        /// </summary>
        public static string ButtonShareAccess {
            get {
                return ResourceManager.GetString("ButtonShareAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Versions.
        /// </summary>
        public static string ButtonShowVersions {
            get {
                return ResourceManager.GetString("ButtonShowVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string ButtonSkip {
            get {
                return ResourceManager.GetString("ButtonSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Slideshow.
        /// </summary>
        public static string ButtonSlideshow {
            get {
                return ResourceManager.GetString("ButtonSlideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string ButtonSortAuthor {
            get {
                return ResourceManager.GetString("ButtonSortAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string ButtonSortModified {
            get {
                return ResourceManager.GetString("ButtonSortModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ButtonSortName {
            get {
                return ResourceManager.GetString("ButtonSortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string ButtonSortSize {
            get {
                return ResourceManager.GetString("ButtonSortSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string ButtonUpload {
            get {
                return ResourceManager.GetString("ButtonUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update document.
        /// </summary>
        public static string ButtonUploadNewVersions {
            get {
                return ResourceManager.GetString("ButtonUploadNewVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, delete.
        /// </summary>
        public static string ButtonYesRemove {
            get {
                return ResourceManager.GetString("ButtonYesRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        public static string ButtonZoomIn {
            get {
                return ResourceManager.GetString("ButtonZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        public static string ButtonZoomOut {
            get {
                return ResourceManager.GetString("ButtonZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite confirmation.
        /// </summary>
        public static string ConfirmOverwrite {
            get {
                return ResourceManager.GetString("ConfirmOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string ConfirmRemove {
            get {
                return ResourceManager.GetString("ConfirmRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: This action can not be undone. .
        /// </summary>
        public static string ConfirmRemoveDescription {
            get {
                return ResourceManager.GetString("ConfirmRemoveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Documents.
        /// </summary>
        public static string CorporateFiles {
            get {
                return ResourceManager.GetString("CorporateFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date.
        /// </summary>
        public static string CreatingDate {
            get {
                return ResourceManager.GetString("CreatingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        public static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Name.
        /// </summary>
        public static string DocumentName {
            get {
                return ResourceManager.GetString("DocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do not leave the page while the process is in progress..
        /// </summary>
        public static string DoNotLeavePageLabel {
            get {
                return ResourceManager.GetString("DoNotLeavePageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download &amp; Install.
        /// </summary>
        public static string DownloadAndInstall {
            get {
                return ResourceManager.GetString("DownloadAndInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download document.
        /// </summary>
        public static string DownloadFile {
            get {
                return ResourceManager.GetString("DownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download folder.
        /// </summary>
        public static string DownloadFolder {
            get {
                return ResourceManager.GetString("DownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download document.
        /// </summary>
        public static string DownloadLink {
            get {
                return ResourceManager.GetString("DownloadLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Know?.
        /// </summary>
        public static string DoYouKnow {
            get {
                return ResourceManager.GetString("DoYouKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit documents directly on your TeamLab portal. Use virtualized Open Office with no software installation needed..
        /// </summary>
        public static string EditingFeatureDescription {
            get {
                return ResourceManager.GetString("EditingFeatureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing.
        /// </summary>
        public static string EditingFeatureHeader {
            get {
                return ResourceManager.GetString("EditingFeatureHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section doesn&apos;t contain files to preview.
        /// </summary>
        public static string EmptyContainer {
            get {
                return ResourceManager.GetString("EmptyContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text files,  spreadsheets, images.
        /// </summary>
        public static string EmptyFolderDescribe {
            get {
                return ResourceManager.GetString("EmptyFolderDescribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The uploaded file was not found.
        /// </summary>
        public static string ErrorEmptyUploadFileSelected {
            get {
                return ResourceManager.GetString("ErrorEmptyUploadFileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Users.
        /// </summary>
        public static string Everyone {
            get {
                return ResourceManager.GetString("Everyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Favorites.
        /// </summary>
        public static string FavoritesCaption {
            get {
                return ResourceManager.GetString("FavoritesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Favorites.
        /// </summary>
        public static string FavoritesCaptionRemove {
            get {
                return ResourceManager.GetString("FavoritesCaptionRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string FavoritesDescribe {
            get {
                return ResourceManager.GetString("FavoritesDescribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you add documents to Favorites you will always have a quick access to your frequently used files and folders stored in your personal or corporate sections..
        /// </summary>
        public static string FavoritesEmpty {
            get {
                return ResourceManager.GetString("FavoritesEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string FilterAllButton {
            get {
                return ResourceManager.GetString("FilterAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload with Flash.
        /// </summary>
        public static string FlashUploader {
            get {
                return ResourceManager.GetString("FlashUploader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash uploader version....
        /// </summary>
        public static string FlashUploaderDescription {
            get {
                return ResourceManager.GetString("FlashUploaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string Folders {
            get {
                return ResourceManager.GetString("Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to file.
        /// </summary>
        public static string GetLinkDescribe {
            get {
                return ResourceManager.GetString("GetLinkDescribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get link to file.
        /// </summary>
        public static string GetLinkDialog {
            get {
                return ResourceManager.GetString("GetLinkDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Link.
        /// </summary>
        public static string GetShortLink {
            get {
                return ResourceManager.GetString("GetShortLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the group?.
        /// </summary>
        public static string GroupConfirmRemove {
            get {
                return ResourceManager.GetString("GroupConfirmRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting.
        /// </summary>
        public static string GroupRemoveHeader {
            get {
                return ResourceManager.GetString("GroupRemoveHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string GroupsTabName {
            get {
                return ResourceManager.GetString("GroupsTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Title.
        /// </summary>
        public static string GroupTitle {
            get {
                return ResourceManager.GetString("GroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability to create and edit documents on portal became possible with a specially
        ///                developed virtualization technology. On the user&apos;s side the technology is activated
        ///                in 3 steps:.
        /// </summary>
        public static string HowItWorksDescription {
            get {
                return ResourceManager.GetString("HowItWorksDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How it works?.
        /// </summary>
        public static string HowItWorksHeader {
            get {
                return ResourceManager.GetString("HowItWorksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now you can launch Open Office right on your portal!.
        /// </summary>
        public static string HowItWorksOpportunitiesAvailable {
            get {
                return ResourceManager.GetString("HowItWorksOpportunitiesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is required for correct download, performance and update of virtualized Open
        ///                        Office. One time installed, {0}ASC Plug-in{1}  will be updated automatically..
        /// </summary>
        public static string HowItWorksStepOneDescription {
            get {
                return ResourceManager.GetString("HowItWorksStepOneDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascensio System Plug-in installation..
        /// </summary>
        public static string HowItWorksStepOneHeader {
            get {
                return ResourceManager.GetString("HowItWorksStepOneHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application archive is unpacked..
        /// </summary>
        public static string HowItWorksStepThreeDescription {
            get {
                return ResourceManager.GetString("HowItWorksStepThreeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Office unpacking..
        /// </summary>
        public static string HowItWorksStepThreeHeader {
            get {
                return ResourceManager.GetString("HowItWorksStepThreeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Office is packed in the archive with all system components necessary for application
        ///                        functioning in browser. For this reason the download may take some considerable
        ///                        time depending on Internet connection speed..
        /// </summary>
        public static string HowItWorksStepTwoDescription {
            get {
                return ResourceManager.GetString("HowItWorksStepTwoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Office download..
        /// </summary>
        public static string HowItWorksStepTwoHeader {
            get {
                return ResourceManager.GetString("HowItWorksStepTwoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch video to see how it works..
        /// </summary>
        public static string HowItWorksWatchVideo {
            get {
                return ResourceManager.GetString("HowItWorksWatchVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload with Html.
        /// </summary>
        public static string HtmlUploader {
            get {
                return ResourceManager.GetString("HtmlUploader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case of file conflict .
        /// </summary>
        public static string IfFileNameConflict {
            get {
                return ResourceManager.GetString("IfFileNameConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        public static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import your current documents base from Google Docs, Zoho, Box.net to TeamLab Docs
        ///                        in a few steps..
        /// </summary>
        public static string ImportFeatureDescription {
            get {
                return ResourceManager.GetString("ImportFeatureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string ImportFeatureHeader {
            get {
                return ResourceManager.GetString("ImportFeatureHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from Box.Net.
        /// </summary>
        public static string ImportFromBoxNet {
            get {
                return ResourceManager.GetString("ImportFromBoxNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from Google Docs.
        /// </summary>
        public static string ImportFromGoogle {
            get {
                return ResourceManager.GetString("ImportFromGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from Zoho.
        /// </summary>
        public static string ImportFromZoho {
            get {
                return ResourceManager.GetString("ImportFromZoho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import in progress.
        /// </summary>
        public static string ImportProgress {
            get {
                return ResourceManager.GetString("ImportProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import to the folder.
        /// </summary>
        public static string ImportToFolder {
            get {
                return ResourceManager.GetString("ImportToFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting.
        /// </summary>
        public static string InstallPluginHeader {
            get {
                return ResourceManager.GetString("InstallPluginHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrate documents into the Projects Management module. Use a special tab in each project section to access necessary docs..
        /// </summary>
        public static string IntegrationFeatureDescription {
            get {
                return ResourceManager.GetString("IntegrationFeatureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration.
        /// </summary>
        public static string IntegrationFeatureHeader {
            get {
                return ResourceManager.GetString("IntegrationFeatureHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show group operations.
        /// </summary>
        public static string MainHeaderActionsOpen {
            get {
                return ResourceManager.GetString("MainHeaderActionsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show:.
        /// </summary>
        public static string MainHeaderFilter {
            get {
                return ResourceManager.GetString("MainHeaderFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a filter value.
        /// </summary>
        public static string MainHeaderFilterOpen {
            get {
                return ResourceManager.GetString("MainHeaderFilterOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string MainHeaderSelectAll {
            get {
                return ResourceManager.GetString("MainHeaderSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by:.
        /// </summary>
        public static string MainHeaderSort {
            get {
                return ResourceManager.GetString("MainHeaderSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a field to sort by.
        /// </summary>
        public static string MainHeaderSortOpen {
            get {
                return ResourceManager.GetString("MainHeaderSortOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organize your private files storage. Share documents with your colleagues. Publish
        ///                        corporate data for all team members..
        /// </summary>
        public static string ManagementFeatureDescription {
            get {
                return ResourceManager.GetString("ManagementFeatureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string ManagementFeatureHeader {
            get {
                return ResourceManager.GetString("ManagementFeatureHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group management.
        /// </summary>
        public static string ManagmentGroup {
            get {
                return ResourceManager.GetString("ManagmentGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or {0}drag&apos;n&apos;drop{1} them from your desktop.
        /// </summary>
        public static string MoveFromDesktop {
            get {
                return ResourceManager.GetString("MoveFromDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Documents.
        /// </summary>
        public static string MyFiles {
            get {
                return ResourceManager.GetString("MyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New File.
        /// </summary>
        public static string NewFile {
            get {
                return ResourceManager.GetString("NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file size cannot exceed {1}{0} Mb{2}..
        /// </summary>
        public static string NoteFileUpload {
            get {
                return ResourceManager.GetString("NoteFileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get messages notifying about documents changes. Be informed when a file was updated or deleted..
        /// </summary>
        public static string NotificationFeatureDescription {
            get {
                return ResourceManager.GetString("NotificationFeatureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string NotificationFeatureHeader {
            get {
                return ResourceManager.GetString("NotificationFeatureHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview in new window.
        /// </summary>
        public static string OpenFileBlank {
            get {
                return ResourceManager.GetString("OpenFileBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Tree.
        /// </summary>
        public static string OpenTree {
            get {
                return ResourceManager.GetString("OpenTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite.
        /// </summary>
        public static string Overwrite {
            get {
                return ResourceManager.GetString("Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! Possibly this file is a renamed executable file and it cannot be previewed..
        /// </summary>
        public static string PreviewError {
            get {
                return ResourceManager.GetString("PreviewError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you trust this file distributor, download and execute it locally..
        /// </summary>
        public static string PreviewErrorDownload {
            get {
                return ResourceManager.GetString("PreviewErrorDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview documents.
        /// </summary>
        public static string PreviewHeader {
            get {
                return ResourceManager.GetString("PreviewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File conversion in process. This may take some time. Please wait....
        /// </summary>
        public static string PreviewWait {
            get {
                return ResourceManager.GetString("PreviewWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication process....
        /// </summary>
        public static string ProcessAuthentificate {
            get {
                return ResourceManager.GetString("ProcessAuthentificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a web application for internal use designed to store and share files and work on them in team..
        /// </summary>
        public static string ProductDescription {
            get {
                return ResourceManager.GetString("ProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project documents.
        /// </summary>
        public static string ProjectFiles {
            get {
                return ResourceManager.GetString("ProjectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quota usage.
        /// </summary>
        public static string QuotaUsage {
            get {
                return ResourceManager.GetString("QuotaUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder.
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Settings.
        /// </summary>
        public static string ShareAccessHeader {
            get {
                return ResourceManager.GetString("ShareAccessHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared with Me.
        /// </summary>
        public static string SharedForMe {
            get {
                return ResourceManager.GetString("SharedForMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter documents according to their type, users, author&apos;s departments or sort them by name, date, author and size..
        /// </summary>
        public static string SortingFeatureDescription {
            get {
                return ResourceManager.GetString("SortingFeatureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting.
        /// </summary>
        public static string SortingFeatureHeader {
            get {
                return ResourceManager.GetString("SortingFeatureHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total found.
        /// </summary>
        public static string TotalFound {
            get {
                return ResourceManager.GetString("TotalFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash.
        /// </summary>
        public static string Trash {
            get {
                return ResourceManager.GetString("Trash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        public static string Types {
            get {
                return ResourceManager.GetString("Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfollow.
        /// </summary>
        public static string Unsubscribe {
            get {
                return ResourceManager.GetString("Unsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees in Group.
        /// </summary>
        public static string UsersInGroup {
            get {
                return ResourceManager.GetString("UsersInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UsersTabName {
            get {
                return ResourceManager.GetString("UsersTabName", resourceCulture);
            }
        }
    }
}
