//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.Files.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FilesJSResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FilesJSResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.Files.Resources.FilesJSResource", typeof(FilesJSResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixed permissions.
        /// </summary>
        public static string AceStatusEnum_DiffRoles {
            get {
                return ResourceManager.GetString("AceStatusEnum_DiffRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string AceStatusEnum_Owner {
            get {
                return ResourceManager.GetString("AceStatusEnum_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Only.
        /// </summary>
        public static string AceStatusEnum_Read {
            get {
                return ResourceManager.GetString("AceStatusEnum_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Access.
        /// </summary>
        public static string AceStatusEnum_ReadWrite {
            get {
                return ResourceManager.GetString("AceStatusEnum_ReadWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny Access.
        /// </summary>
        public static string AceStatusEnum_Restrict {
            get {
                return ResourceManager.GetString("AceStatusEnum_Restrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Favorites.
        /// </summary>
        public static string AddToFavorites {
            get {
                return ResourceManager.GetString("AddToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        public static string BreadCrumbsSeparator {
            get {
                return ResourceManager.GetString("BreadCrumbsSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Files.
        /// </summary>
        public static string ButtonAddFiles {
            get {
                return ResourceManager.GetString("ButtonAddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Files.
        /// </summary>
        public static string ButtonSelectFiles {
            get {
                return ResourceManager.GetString("ButtonSelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more {0}.
        /// </summary>
        public static string ButtonShowMore {
            get {
                return ResourceManager.GetString("ButtonShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading....
        /// </summary>
        public static string ButtonShowMoreLoad {
            get {
                return ResourceManager.GetString("ButtonShowMoreLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more {0} of {1}.
        /// </summary>
        public static string ButtonShowMoreOf {
            get {
                return ResourceManager.GetString("ButtonShowMoreOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} changes in {1}.
        /// </summary>
        public static string ChangedItemHeader {
            get {
                return ResourceManager.GetString("ChangedItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to empty the trash?.
        /// </summary>
        public static string ConfirmEmptyTrash {
            get {
                return ResourceManager.GetString("ConfirmEmptyTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the document?.
        /// </summary>
        public static string ConfirmRemoveFile {
            get {
                return ResourceManager.GetString("ConfirmRemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the folder?.
        /// </summary>
        public static string ConfirmRemoveFolder {
            get {
                return ResourceManager.GetString("ConfirmRemoveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete these elements?.
        /// </summary>
        public static string ConfirmRemoveList {
            get {
                return ResourceManager.GetString("ConfirmRemoveList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Documents.
        /// </summary>
        public static string CorporateFiles {
            get {
                return ResourceManager.GetString("CorporateFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Group.
        /// </summary>
        public static string CreateGroup {
            get {
                return ResourceManager.GetString("CreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Archiving.
        /// </summary>
        public static string DescriptBulkdownload {
            get {
                return ResourceManager.GetString("DescriptBulkdownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string DescriptCopy {
            get {
                return ResourceManager.GetString("DescriptCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation.
        /// </summary>
        public static string DescriptCreate {
            get {
                return ResourceManager.GetString("DescriptCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading versions....
        /// </summary>
        public static string DescriptLoadVersion {
            get {
                return ResourceManager.GetString("DescriptLoadVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string DescriptMove {
            get {
                return ResourceManager.GetString("DescriptMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting....
        /// </summary>
        public static string DescriptRemove {
            get {
                return ResourceManager.GetString("DescriptRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string DescriptRename {
            get {
                return ResourceManager.GetString("DescriptRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating version.
        /// </summary>
        public static string DescriptSetVersion {
            get {
                return ResourceManager.GetString("DescriptSetVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Group.
        /// </summary>
        public static string EditGroup {
            get {
                return ResourceManager.GetString("EditGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to import.
        /// </summary>
        public static string EmptyDataToImport {
            get {
                return ResourceManager.GetString("EmptyDataToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one folder/document to download.
        /// </summary>
        public static string EmptyListSelectedForDownload {
            get {
                return ResourceManager.GetString("EmptyListSelectedForDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one document to import.
        /// </summary>
        public static string EmptyListSelectedForImport {
            get {
                return ResourceManager.GetString("EmptyListSelectedForImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the &apos;Select document&apos; button to upload your files.
        /// </summary>
        public static string EmptyListUpload {
            get {
                return ResourceManager.GetString("EmptyListUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login or password.
        /// </summary>
        public static string ErrorMassage_AuthentificatedFalse {
            get {
                return ResourceManager.GetString("ErrorMassage_AuthentificatedFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot upload file.
        /// </summary>
        public static string ErrorMassage_DnDError {
            get {
                return ResourceManager.GetString("ErrorMassage_DnDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty file.
        /// </summary>
        public static string ErrorMassage_EmptyFile {
            get {
                return ResourceManager.GetString("ErrorMassage_EmptyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields are required to be filled in.
        /// </summary>
        public static string ErrorMassage_FiledsIsEmpty {
            get {
                return ResourceManager.GetString("ErrorMassage_FiledsIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file type isn&apos;t supported.
        /// </summary>
        public static string ErrorMassage_FileTypeText {
            get {
                return ResourceManager.GetString("ErrorMassage_FileTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum file size {0} Mb is exceeded .
        /// </summary>
        public static string ErrorMassage_LimitFileSize {
            get {
                return ResourceManager.GetString("ErrorMassage_LimitFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for the previous download to complete or cancel it.
        /// </summary>
        public static string ErrorMassage_SecondDownload {
            get {
                return ResourceManager.GetString("ErrorMassage_SecondDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough permission to perform the operation.
        /// </summary>
        public static string ErrorMassage_SecurityException {
            get {
                return ResourceManager.GetString("ErrorMassage_SecurityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove {0} from Favorites?.
        /// </summary>
        public static string FavoritesRemove {
            get {
                return ResourceManager.GetString("FavoritesRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is being edited.
        /// </summary>
        public static string FileAlreadyEdit {
            get {
                return ResourceManager.GetString("FileAlreadyEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file with the name {0} already exists in the folder {1}..
        /// </summary>
        public static string FileAlreadyExist {
            get {
                return ResourceManager.GetString("FileAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the selected file does not match the previous version name!.
        /// </summary>
        public static string FileNameIsNotEqual {
            get {
                return ResourceManager.GetString("FileNameIsNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} documents with the same name already exist in the folder &apos;{1}&apos;. Overwrite the files?.
        /// </summary>
        public static string FilesAlreadyExist {
            get {
                return ResourceManager.GetString("FilesAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading file .
        /// </summary>
        public static string FileUploading {
            get {
                return ResourceManager.GetString("FileUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of the file {0} was successfully restored.
        /// </summary>
        public static string FileVersionRecovery {
            get {
                return ResourceManager.GetString("FileVersionRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from Box.Net.
        /// </summary>
        public static string ImportFromBoxNet {
            get {
                return ResourceManager.GetString("ImportFromBoxNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from Google Docs.
        /// </summary>
        public static string ImportFromGoogle {
            get {
                return ResourceManager.GetString("ImportFromGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from Zoho.
        /// </summary>
        public static string ImportFromZoho {
            get {
                return ResourceManager.GetString("ImportFromZoho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore it from the Trash to perform the operation.
        /// </summary>
        public static string InfoActionInTrash {
            get {
                return ResourceManager.GetString("InfoActionInTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; added to Favorites.
        /// </summary>
        public static string InfoAddFavorite {
            get {
                return ResourceManager.GetString("InfoAddFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming soon.
        /// </summary>
        public static string InfoCommingSoon {
            get {
                return ResourceManager.GetString("InfoCommingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} copied elements.
        /// </summary>
        public static string InfoCopyGroup {
            get {
                return ResourceManager.GetString("InfoCopyGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; copied.
        /// </summary>
        public static string InfoCopyItem {
            get {
                return ResourceManager.GetString("InfoCopyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New file &apos;{0}&apos; is created.
        /// </summary>
        public static string InfoCrateFile {
            get {
                return ResourceManager.GetString("InfoCrateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New folder &apos;{0}&apos; is created.
        /// </summary>
        public static string InfoCrateFolder {
            get {
                return ResourceManager.GetString("InfoCrateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one folder/document to provide access .
        /// </summary>
        public static string InfoEmptyForShare {
            get {
                return ResourceManager.GetString("InfoEmptyForShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import is completed.
        /// </summary>
        public static string InfoFinishImprot {
            get {
                return ResourceManager.GetString("InfoFinishImprot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot copy the folder to its subfolder.
        /// </summary>
        public static string InfoFolderCopyError {
            get {
                return ResourceManager.GetString("InfoFolderCopyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot move the folder to its subfolder.
        /// </summary>
        public static string InfoFolderMoveError {
            get {
                return ResourceManager.GetString("InfoFolderMoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for the previous import to complete.
        /// </summary>
        public static string InfoImprotNotFinish {
            get {
                return ResourceManager.GetString("InfoImprotNotFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} moved elements.
        /// </summary>
        public static string InfoMoveGroup {
            get {
                return ResourceManager.GetString("InfoMoveGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; moved.
        /// </summary>
        public static string InfoMoveItem {
            get {
                return ResourceManager.GetString("InfoMoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted by Author.
        /// </summary>
        public static string InfoOrderByAuthor {
            get {
                return ResourceManager.GetString("InfoOrderByAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted by Date.
        /// </summary>
        public static string InfoOrderByModified {
            get {
                return ResourceManager.GetString("InfoOrderByModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted by Size.
        /// </summary>
        public static string InfoOrderBySize {
            get {
                return ResourceManager.GetString("InfoOrderBySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted by Name.
        /// </summary>
        public static string InfoOrderByTitle {
            get {
                return ResourceManager.GetString("InfoOrderByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; removed from Favorites.
        /// </summary>
        public static string InfoRemoveFavorites {
            get {
                return ResourceManager.GetString("InfoRemoveFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document &apos;{0}&apos; is deleted.
        /// </summary>
        public static string InfoRemoveFile {
            get {
                return ResourceManager.GetString("InfoRemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder &apos;{0}&apos; is deleted.
        /// </summary>
        public static string InfoRemoveFolder {
            get {
                return ResourceManager.GetString("InfoRemoveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was successfully deleted {0} from {1}.
        /// </summary>
        public static string InfoRemoveGroup {
            get {
                return ResourceManager.GetString("InfoRemoveGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document &apos;{0}&apos; is renamed to &apos;{1}&apos;.
        /// </summary>
        public static string InfoRenameFile {
            get {
                return ResourceManager.GetString("InfoRenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder &apos;{0}&apos; is renamed to &apos;{1}&apos;.
        /// </summary>
        public static string InfoRenameFolder {
            get {
                return ResourceManager.GetString("InfoRenameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements: {0}.
        /// </summary>
        public static string InfoSelectCount {
            get {
                return ResourceManager.GetString("InfoSelectCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one element to set access rights.
        /// </summary>
        public static string InfoSelectForShare {
            get {
                return ResourceManager.GetString("InfoSelectForShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Drag the element(s) with the mouse to add to the folder.
        /// </summary>
        public static string InfoSelectingDescribe {
            get {
                return ResourceManager.GetString("InfoSelectingDescribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} documents are successfully uploaded.
        /// </summary>
        public static string InfoUploadedSuccess {
            get {
                return ResourceManager.GetString("InfoUploadedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery View.
        /// </summary>
        public static string InfoViewFolderGallery {
            get {
                return ResourceManager.GetString("InfoViewFolderGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List View .
        /// </summary>
        public static string InfoViewFolderList {
            get {
                return ResourceManager.GetString("InfoViewFolderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string InstallOpenOfficeButton {
            get {
                return ResourceManager.GetString("InstallOpenOfficeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffering is over. Open Office is ready to launch..
        /// </summary>
        public static string InstallOpenOfficeCongratulation {
            get {
                return ResourceManager.GetString("InstallOpenOfficeCongratulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See how it works?.
        /// </summary>
        public static string InstallOpenOfficeDescription {
            get {
                return ResourceManager.GetString("InstallOpenOfficeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To create and edit documents on your portal, please download virtualized Open Office..
        /// </summary>
        public static string InstallOpenOfficeHeader {
            get {
                return ResourceManager.GetString("InstallOpenOfficeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string InstallPluginButton {
            get {
                return ResourceManager.GetString("InstallPluginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASC Plug-in allows you to launch Open Office on portal. {0}See how it works.{1}.
        /// </summary>
        public static string InstallPluginDescription {
            get {
                return ResourceManager.GetString("InstallPluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To create and edit documents on portal, please install Ascensio System Plug-in..
        /// </summary>
        public static string InstallPluginHeader {
            get {
                return ResourceManager.GetString("InstallPluginHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingProcessing {
            get {
                return ResourceManager.GetString("LoadingProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string LoadingWait {
            get {
                return ResourceManager.GetString("LoadingWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Documents.
        /// </summary>
        public static string MyFiles {
            get {
                return ResourceManager.GetString("MyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} new).
        /// </summary>
        public static string NewInShare {
            get {
                return ResourceManager.GetString("NewInShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Office download is in process. Please wait....
        /// </summary>
        public static string OpenOfficeDownloading {
            get {
                return ResourceManager.GetString("OpenOfficeDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded {0} Mb of {1} Mb.
        /// </summary>
        public static string OpenOfficeDownloadingInfo {
            get {
                return ResourceManager.GetString("OpenOfficeDownloadingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Office unpacking is in process. Please wait....
        /// </summary>
        public static string OpenOfficeUnpacking {
            get {
                return ResourceManager.GetString("OpenOfficeUnpacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or drag and drop them to this window.
        /// </summary>
        public static string OrDragDrop {
            get {
                return ResourceManager.GetString("OrDragDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Progress.
        /// </summary>
        public static string OverallProgress {
            get {
                return ResourceManager.GetString("OverallProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uploaded {0} from {1}.
        /// </summary>
        public static string ProcessUploadCountFiles {
            get {
                return ResourceManager.GetString("ProcessUploadCountFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project documents.
        /// </summary>
        public static string ProjectFiles {
            get {
                return ResourceManager.GetString("ProjectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Favorites.
        /// </summary>
        public static string RemoveFavorites {
            get {
                return ResourceManager.GetString("RemoveFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files selected.
        /// </summary>
        public static string SelectedFiles {
            get {
                return ResourceManager.GetString("SelectedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select files to upload.
        /// </summary>
        public static string SelectFilesToUpload {
            get {
                return ResourceManager.GetString("SelectFilesToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string SelectFilterValue {
            get {
                return ResourceManager.GetString("SelectFilterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select.
        /// </summary>
        public static string SelectRight {
            get {
                return ResourceManager.GetString("SelectRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Archiving.
        /// </summary>
        public static string TasksOperationBulkdownload {
            get {
                return ResourceManager.GetString("TasksOperationBulkdownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying.
        /// </summary>
        public static string TasksOperationCopy {
            get {
                return ResourceManager.GetString("TasksOperationCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting.
        /// </summary>
        public static string TasksOperationDelete {
            get {
                return ResourceManager.GetString("TasksOperationDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} operations.
        /// </summary>
        public static string TasksOperationMixed {
            get {
                return ResourceManager.GetString("TasksOperationMixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string TasksOperationMove {
            get {
                return ResourceManager.GetString("TasksOperationMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TitleCancel {
            get {
                return ResourceManager.GetString("TitleCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string TitleCreate {
            get {
                return ResourceManager.GetString("TitleCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Presentation.
        /// </summary>
        public static string TitleNewFilePresentation {
            get {
                return ResourceManager.GetString("TitleNewFilePresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Spreadsheet.
        /// </summary>
        public static string TitleNewFileSpreadsheet {
            get {
                return ResourceManager.GetString("TitleNewFileSpreadsheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New File.
        /// </summary>
        public static string TitleNewFileText {
            get {
                return ResourceManager.GetString("TitleNewFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        public static string TitleNewFolder {
            get {
                return ResourceManager.GetString("TitleNewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string TitleRename {
            get {
                return ResourceManager.GetString("TitleRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update file version.
        /// </summary>
        public static string UpdateFileVersionFor {
            get {
                return ResourceManager.GetString("UpdateFileVersionFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Office updates are available. Download now..
        /// </summary>
        public static string UpdateOpenOfficeHeader {
            get {
                return ResourceManager.GetString("UpdateOpenOfficeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / {1} uploaded files.
        /// </summary>
        public static string UploadedOf {
            get {
                return ResourceManager.GetString("UploadedOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload document to.
        /// </summary>
        public static string UploadFileTo {
            get {
                return ResourceManager.GetString("UploadFileTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading.
        /// </summary>
        public static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploading process....
        /// </summary>
        public static string UploadProcess {
            get {
                return ResourceManager.GetString("UploadProcess", resourceCulture);
            }
        }
    }
}
