//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.Projects.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.Projects.Resources.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached Files.
        /// </summary>
        public static string AttachedFiles {
            get {
                return ResourceManager.GetString("AttachedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start discussion.
        /// </summary>
        public static string CreateMessage {
            get {
                return ResourceManager.GetString("CreateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete discussion.
        /// </summary>
        public static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit discussion.
        /// </summary>
        public static string EditMessage {
            get {
                return ResourceManager.GetString("EditMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the first discussion in this project.
        /// </summary>
        public static string EmptyScreenHeaderContent {
            get {
                return ResourceManager.GetString("EmptyScreenHeaderContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange text messages within the project..
        /// </summary>
        public static string EmptyScreenHeaderDescribe {
            get {
                return ResourceManager.GetString("EmptyScreenHeaderDescribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the first discussion in this project template.
        /// </summary>
        public static string EmptyScreenMessageTemplate {
            get {
                return ResourceManager.GetString("EmptyScreenMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a welcome message, post answers to common questions or publish an important document for each project you create..
        /// </summary>
        public static string EmptyScreenMessageTemplateDescription {
            get {
                return ResourceManager.GetString("EmptyScreenMessageTemplateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Subscribers.
        /// </summary>
        public static string ManageSubscribers {
            get {
                return ResourceManager.GetString("ManageSubscribers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discussion.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string MessageContent {
            get {
                return ResourceManager.GetString("MessageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probably it has been deleted, or there are no messages with such ID in the project.
        /// </summary>
        public static string MessageNotFound_Body {
            get {
                return ResourceManager.GetString("MessageNotFound_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message not found.
        /// </summary>
        public static string MessageNotFound_Header {
            get {
                return ResourceManager.GetString("MessageNotFound_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the message list.
        /// </summary>
        public static string MessageNotFound_RedirectTitle {
            get {
                return ResourceManager.GetString("MessageNotFound_RedirectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discussions.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string MessageTitle {
            get {
                return ResourceManager.GetString("MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Discussion.
        /// </summary>
        public static string NewMessage {
            get {
                return ResourceManager.GetString("NewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify people out of the project.
        /// </summary>
        public static string NotifyMorePeopleOutOfTheProject {
            get {
                return ResourceManager.GetString("NotifyMorePeopleOutOfTheProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave comment.
        /// </summary>
        public static string PostNewComment {
            get {
                return ResourceManager.GetString("PostNewComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add This Message.
        /// </summary>
        public static string PostThisMessage {
            get {
                return ResourceManager.GetString("PostThisMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving message....
        /// </summary>
        public static string SavingMessage {
            get {
                return ResourceManager.GetString("SavingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more.
        /// </summary>
        public static string SeeMore {
            get {
                return ResourceManager.GetString("SeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Users.
        /// </summary>
        public static string SelectUsers {
            get {
                return ResourceManager.GetString("SelectUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inform other people as well.
        /// </summary>
        public static string SubscribeAnotherPeopleInfo {
            get {
                return ResourceManager.GetString("SubscribeAnotherPeopleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite project participants to discussion.
        /// </summary>
        public static string SubscribePeopleInfo {
            get {
                return ResourceManager.GetString("SubscribePeopleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The people you select will be informed about the message and the comments to it..
        /// </summary>
        public static string SubscribePeopleInfoComment {
            get {
                return ResourceManager.GetString("SubscribePeopleInfoComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify the selected users about the change of this message?.
        /// </summary>
        public static string SubscribePeopleInfoEdit {
            get {
                return ResourceManager.GetString("SubscribePeopleInfoEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify.
        /// </summary>
        public static string SubscribeUsers {
            get {
                return ResourceManager.GetString("SubscribeUsers", resourceCulture);
            }
        }
    }
}
