//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.Projects.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProjectsJSResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectsJSResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.Projects.Resources.ProjectsJSResource", typeof(ProjectsJSResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new task.
        /// </summary>
        public static string AddNewTask {
            get {
                return ResourceManager.GetString("AddNewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add This Task.
        /// </summary>
        public static string AddThisTask {
            get {
                return ResourceManager.GetString("AddThisTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string B {
            get {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category has been successfully changed.
        /// </summary>
        public static string CategoryChangedSuccessfully {
            get {
                return ResourceManager.GetString("CategoryChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file to upload.
        /// </summary>
        public static string ChooseAFileToUpload {
            get {
                return ResourceManager.GetString("ChooseAFileToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot complete this milestone as there are active tasks assigned to it..
        /// </summary>
        public static string ClosedStatusFunctionIsLocked {
            get {
                return ResourceManager.GetString("ClosedStatusFunctionIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string Collapse {
            get {
                return ResourceManager.GetString("Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All tasks will be deleted.\nNote: this action cannot be undone..
        /// </summary>
        public static string ConfirmClearTrash {
            get {
                return ResourceManager.GetString("ConfirmClearTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the {0} file?\nNote: this action cannot be undone..
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the template(s)?.
        /// </summary>
        public static string ConfirmTemplateDeleting {
            get {
                return ResourceManager.GetString("ConfirmTemplateDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new task.
        /// </summary>
        public static string CreateNewTask {
            get {
                return ResourceManager.GetString("CreateNewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the {0} file?\nNote: this action cannot be undone..
        /// </summary>
        public static string DeleteThisFile {
            get {
                return ResourceManager.GetString("DeleteThisFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this message?\nNote: this action cannot be undone..
        /// </summary>
        public static string DeleteThisMessage {
            get {
                return ResourceManager.GetString("DeleteThisMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this milestone?\nNote: this action cannot be undone..
        /// </summary>
        public static string DeleteThisMilectone {
            get {
                return ResourceManager.GetString("DeleteThisMilectone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the project?\nNote: this action cannot be undone..
        /// </summary>
        public static string DeleteThisProject {
            get {
                return ResourceManager.GetString("DeleteThisProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this project template?\nNote: this action cannot be undone..
        /// </summary>
        public static string DeleteThisProjectTemplate {
            get {
                return ResourceManager.GetString("DeleteThisProjectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the {0} task?\nNote: this action cannot be undone..
        /// </summary>
        public static string DeleteThisTask {
            get {
                return ResourceManager.GetString("DeleteThisTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Categories.
        /// </summary>
        public static string EditCategories {
            get {
                return ResourceManager.GetString("EditCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot edit the milestone as it already contains tasks..
        /// </summary>
        public static string EditFunctionIsLocked {
            get {
                return ResourceManager.GetString("EditFunctionIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit task.
        /// </summary>
        public static string EditThisTask {
            get {
                return ResourceManager.GetString("EditThisTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please describe what you spent this time for..
        /// </summary>
        public static string EmptyDescription {
            get {
                return ResourceManager.GetString("EmptyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set a time spent.
        /// </summary>
        public static string EmptyHoursCount {
            get {
                return ResourceManager.GetString("EmptyHoursCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each message must have a title.
        /// </summary>
        public static string EmptyMessageTitle {
            get {
                return ResourceManager.GetString("EmptyMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each project must have a manager.
        /// </summary>
        public static string EmptyProjectManager {
            get {
                return ResourceManager.GetString("EmptyProjectManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each project must have a title.
        /// </summary>
        public static string EmptyProjectTitle {
            get {
                return ResourceManager.GetString("EmptyProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each task must have a title.
        /// </summary>
        public static string EmptyTaskTitle {
            get {
                return ResourceManager.GetString("EmptyTaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Could not change category. Refresh the page and try again..
        /// </summary>
        public static string ErrorCategoryNotChanged {
            get {
                return ResourceManager.GetString("ErrorCategoryNotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Expand {
            get {
                return ResourceManager.GetString("Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: the file size cannot exceed 100 MB..
        /// </summary>
        public static string FileSizeNote {
            get {
                return ResourceManager.GetString("FileSizeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Filters.
        /// </summary>
        public static string HideFilters {
            get {
                return ResourceManager.GetString("HideFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Template.
        /// </summary>
        public static string HideTemplate {
            get {
                return ResourceManager.GetString("HideTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date format is invalid.
        /// </summary>
        public static string IncorrectDate {
            get {
                return ResourceManager.GetString("IncorrectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kb.
        /// </summary>
        public static string kB {
            get {
                return ResourceManager.GetString("kB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mb.
        /// </summary>
        public static string MB {
            get {
                return ResourceManager.GetString("MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project manager has been sent a notification about the troubleshooting completed..
        /// </summary>
        public static string NotifyManagerAboutIssueCompleted {
            get {
                return ResourceManager.GetString("NotifyManagerAboutIssueCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project manager has been sent a notification about completing the task.
        /// </summary>
        public static string NotifyManagerAboutTaskCompleted {
            get {
                return ResourceManager.GetString("NotifyManagerAboutTaskCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The responsible party has been sent a notification.
        /// </summary>
        public static string NotifyResponsibleAboutTask {
            get {
                return ResourceManager.GetString("NotifyResponsibleAboutTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may plan only one milestone a day .
        /// </summary>
        public static string OnlyOneMilestone {
            get {
                return ResourceManager.GetString("OnlyOneMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No employees in project.
        /// </summary>
        public static string ProjectTeamIsNull {
            get {
                return ResourceManager.GetString("ProjectTeamIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving message....
        /// </summary>
        public static string SavingMessage {
            get {
                return ResourceManager.GetString("SavingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an action.
        /// </summary>
        public static string SelectedActionInfo {
            get {
                return ResourceManager.GetString("SelectedActionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select tasks.
        /// </summary>
        public static string SelectedTasksInfo {
            get {
                return ResourceManager.GetString("SelectedTasksInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select templates.
        /// </summary>
        public static string SelectedTemplatesInfo {
            get {
                return ResourceManager.GetString("SelectedTemplatesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Project Tasks.
        /// </summary>
        public static string SwitchToTaskList {
            get {
                return ResourceManager.GetString("SwitchToTaskList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Personal To-Do.
        /// </summary>
        public static string SwitchToToDoList {
            get {
                return ResourceManager.GetString("SwitchToToDoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project manager will receive a notification email.
        /// </summary>
        public static string TaskActionCreateInfoBlock {
            get {
                return ResourceManager.GetString("TaskActionCreateInfoBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trash is empty..
        /// </summary>
        public static string TrashEmpty {
            get {
                return ResourceManager.GetString("TrashEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled Milestone.
        /// </summary>
        public static string UntitledMilestone {
            get {
                return ResourceManager.GetString("UntitledMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading....
        /// </summary>
        public static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded.
        /// </summary>
        public static string UploadingCompleted {
            get {
                return ResourceManager.GetString("UploadingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading file «{0}».....
        /// </summary>
        public static string UploadingFile {
            get {
                return ResourceManager.GetString("UploadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Filters.
        /// </summary>
        public static string ViewFilters {
            get {
                return ResourceManager.GetString("ViewFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Template.
        /// </summary>
        public static string ViewTemplate {
            get {
                return ResourceManager.GetString("ViewTemplate", resourceCulture);
            }
        }
    }
}
