//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.Projects.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.Projects.Resources.SettingsResource", typeof(SettingsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No permissions for data import.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Window.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company URL, for example {0}https://mycompany.basecamphq.com{1}.
        /// </summary>
        public static string CompanyURL {
            get {
                return ResourceManager.GetString("CompanyURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Tab.
        /// </summary>
        public static string DefaultTab {
            get {
                return ResourceManager.GetString("DefaultTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the tab that will be used as the default home page.
        /// </summary>
        public static string DefaultTabInfo {
            get {
                return ResourceManager.GetString("DefaultTabInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The API Token field is empty.
        /// </summary>
        public static string EmptyToken {
            get {
                return ResourceManager.GetString("EmptyToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL field is empty.
        /// </summary>
        public static string EmptyURL {
            get {
                return ResourceManager.GetString("EmptyURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save comment &quot;{0}&quot;.
        /// </summary>
        public static string FailedToSaveComment {
            get {
                return ResourceManager.GetString("FailedToSaveComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot upload file {0}.
        /// </summary>
        public static string FailedToSaveFile {
            get {
                return ResourceManager.GetString("FailedToSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save file category &quot;{0}&quot;.
        /// </summary>
        public static string FailedToSaveFileCategory {
            get {
                return ResourceManager.GetString("FailedToSaveFileCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save message &quot;{0}&quot;.
        /// </summary>
        public static string FailedToSaveMessage {
            get {
                return ResourceManager.GetString("FailedToSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save milestone &quot;{0}&quot;.
        /// </summary>
        public static string FailedToSaveMilestone {
            get {
                return ResourceManager.GetString("FailedToSaveMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save project &quot;{0}&quot;.
        /// </summary>
        public static string FailedToSaveProject {
            get {
                return ResourceManager.GetString("FailedToSaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faile to save task &quot;{0}&quot;.
        /// </summary>
        public static string FailedToSaveTask {
            get {
                return ResourceManager.GetString("FailedToSaveTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faield to save time item &quot;{0}&quot;.
        /// </summary>
        public static string FailedToSaveTimeSpend {
            get {
                return ResourceManager.GetString("FailedToSaveTimeSpend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save user &quot;{0}&quot;.
        /// </summary>
        public static string FailedToSaveUser {
            get {
                return ResourceManager.GetString("FailedToSaveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I understand it.
        /// </summary>
        public static string ImportAttantionPanelAgreement {
            get {
                return ResourceManager.GetString("ImportAttantionPanelAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Basecamp projects will be imported to TeamLab as Private projects. These projects will be available to the portal&apos;s administrators only. The project managers and the members of the project team will get access to the corresponding projects only..
        /// </summary>
        public static string ImportAttantionPanelBody {
            get {
                return ResourceManager.GetString("ImportAttantionPanelBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        public static string ImportAttantionPanelTitle {
            get {
                return ResourceManager.GetString("ImportAttantionPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import closed tasks and projects.
        /// </summary>
        public static string ImportClosedTasks {
            get {
                return ResourceManager.GetString("ImportClosedTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing completed.
        /// </summary>
        public static string ImportCompleted {
            get {
                return ResourceManager.GetString("ImportCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while importing.
        /// </summary>
        public static string ImportFailed {
            get {
                return ResourceManager.GetString("ImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting import of {0} files from all project.
        /// </summary>
        public static string ImportFileStarted {
            get {
                return ResourceManager.GetString("ImportFileStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from Basecamp.
        /// </summary>
        public static string ImportFromBasecamp {
            get {
                return ResourceManager.GetString("ImportFromBasecamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that all the data imported from your Basecamp account will become public to all portal members as TeamLab doesn&apos;t provide access restrictions..
        /// </summary>
        public static string ImportInfo_Attention {
            get {
                return ResourceManager.GetString("ImportInfo_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention! After Import is completed, all your portal members will get an access to ALL the data from your Basecamp account. Do you agree to proceed?.
        /// </summary>
        public static string ImportInfo_Attention_PopUp {
            get {
                return ResourceManager.GetString("ImportInfo_Attention_PopUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All your portal members will receive email invitations to TeamLab..
        /// </summary>
        public static string ImportInfo_Notyfy {
            get {
                return ResourceManager.GetString("ImportInfo_Notyfy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing....
        /// </summary>
        public static string ImportInfoPanelContent {
            get {
                return ResourceManager.GetString("ImportInfoPanelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started import of project &quot;{0}&quot; data.
        /// </summary>
        public static string ImportProjectDataStarted {
            get {
                return ResourceManager.GetString("ImportProjectDataStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import projects from Basecamp.
        /// </summary>
        public static string ImportProjectsFromTheBaseCamp {
            get {
                return ResourceManager.GetString("ImportProjectsFromTheBaseCamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started import of project &quot;{0}&quot;.
        /// </summary>
        public static string ImportProjectStarted {
            get {
                return ResourceManager.GetString("ImportProjectStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import started.
        /// </summary>
        public static string ImportStarted {
            get {
                return ResourceManager.GetString("ImportStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can block some Projects modules here.
        /// </summary>
        public static string InfoModuleSettings {
            get {
                return ResourceManager.GetString("InfoModuleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basecamp access information is used only once for a single import and is not stored in the system.
        /// </summary>
        public static string InfoToken {
            get {
                return ResourceManager.GetString("InfoToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure {0}Basecamp API{1} is enabled in your Basecamp site settings.
        /// </summary>
        public static string InfoURL {
            get {
                return ResourceManager.GetString("InfoURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL you entered is incorrect.
        /// </summary>
        public static string MalformedUrl {
            get {
                return ResourceManager.GetString("MalformedUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Settings.
        /// </summary>
        public static string ModuleSettings {
            get {
                return ResourceManager.GetString("ModuleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more errors.
        /// </summary>
        public static string MoreErrors {
            get {
                return ResourceManager.GetString("MoreErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL you entered is not a Basecamp company URL.
        /// </summary>
        public static string NotBasecampUrl {
            get {
                return ResourceManager.GetString("NotBasecampUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of 3.
        /// </summary>
        public static string OutOfThree {
            get {
                return ResourceManager.GetString("OutOfThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while the most important part is importing.
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is recommended not to make any changes to your portal while{0}
        ///                            the import is being done.{0}{0}
        ///                            You may close this window and continue working with your TeamLab portal{0}
        ///                           as soon as the import of the Files section starts..
        /// </summary>
        public static string PopupPanelBody {
            get {
                return ResourceManager.GetString("PopupPanelBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing from Basecamp.
        /// </summary>
        public static string PopupPanelHeader {
            get {
                return ResourceManager.GetString("PopupPanelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send email invitations to TeamLab to all portal members.
        /// </summary>
        public static string SendInvitations {
            get {
                return ResourceManager.GetString("SendInvitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Importing.
        /// </summary>
        public static string StartImport {
            get {
                return ResourceManager.GetString("StartImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to awaiting.
        /// </summary>
        public static string StatusAwaiting {
            get {
                return ResourceManager.GetString("StatusAwaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to importing.
        /// </summary>
        public static string StatusImporting {
            get {
                return ResourceManager.GetString("StatusImporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Basecamp API token.
        /// </summary>
        public static string UserToken {
            get {
                return ResourceManager.GetString("UserToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the Calendar module.
        /// </summary>
        public static string ViewCalendar {
            get {
                return ResourceManager.GetString("ViewCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        public static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the Files module.
        /// </summary>
        public static string ViewFiles {
            get {
                return ResourceManager.GetString("ViewFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the Issues module.
        /// </summary>
        public static string ViewIssueTracker {
            get {
                return ResourceManager.GetString("ViewIssueTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the Time Tracking module.
        /// </summary>
        public static string ViewTimeTracking {
            get {
                return ResourceManager.GetString("ViewTimeTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Start Importing.
        /// </summary>
        public static string YesStartImport {
            get {
                return ResourceManager.GetString("YesStartImport", resourceCulture);
            }
        }
    }
}
