//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.Studio.PublicResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SkinNameResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SkinNameResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.Studio.PublicResources.SkinNameResource", typeof(SkinNameResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air.
        /// </summary>
        public static string AirSkin {
            get {
                return ResourceManager.GetString("AirSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string BlueSkin {
            get {
                return ResourceManager.GetString("BlueSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brick.
        /// </summary>
        public static string BrickSkin {
            get {
                return ResourceManager.GetString("BrickSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chestnut.
        /// </summary>
        public static string ChestnutSkin {
            get {
                return ResourceManager.GetString("ChestnutSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string DefaultSkin {
            get {
                return ResourceManager.GetString("DefaultSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emerald.
        /// </summary>
        public static string EmeraldSkin {
            get {
                return ResourceManager.GetString("EmeraldSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        public static string GraySkin {
            get {
                return ResourceManager.GetString("GraySkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sand.
        /// </summary>
        public static string SandSkin {
            get {
                return ResourceManager.GetString("SandSkin", resourceCulture);
            }
        }
    }
}
