//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.Controls.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PollForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PollForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.Controls.Resources.PollForm", typeof(PollForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add poll choice.
        /// </summary>
        internal static string AddAnswerVariantButton {
            get {
                return ResourceManager.GetString("AddAnswerVariantButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of votes.
        /// </summary>
        internal static string AllVoting {
            get {
                return ResourceManager.GetString("AllVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll Choices.
        /// </summary>
        internal static string AnswerVariants {
            get {
                return ResourceManager.GetString("AnswerVariants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select poll choice.
        /// </summary>
        internal static string EmptySelect {
            get {
                return ResourceManager.GetString("EmptySelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow multiple choices for this poll question.
        /// </summary>
        internal static string FewAnswerVariant {
            get {
                return ResourceManager.GetString("FewAnswerVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow only one choice for this poll question.
        /// </summary>
        internal static string OneAnswerVariant {
            get {
                return ResourceManager.GetString("OneAnswerVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll Question.
        /// </summary>
        internal static string PollQuestion {
            get {
                return ResourceManager.GetString("PollQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll Type.
        /// </summary>
        internal static string PollType {
            get {
                return ResourceManager.GetString("PollType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete poll choice.
        /// </summary>
        internal static string RemoveAnswerVariantButton {
            get {
                return ResourceManager.GetString("RemoveAnswerVariantButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice.
        /// </summary>
        internal static string Variant {
            get {
                return ResourceManager.GetString("Variant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote.
        /// </summary>
        internal static string VoteButton {
            get {
                return ResourceManager.GetString("VoteButton", resourceCulture);
            }
        }
    }
}
