//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.Community.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommunityResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommunityResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.Community.Resources.CommunityResource", typeof(CommunityResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows upcoming birthdays.
        /// </summary>
        public static string BirthdayReminderWidgetDescription {
            get {
                return ResourceManager.GetString("BirthdayReminderWidgetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdays.
        /// </summary>
        public static string BirthdayReminderWidgetName {
            get {
                return ResourceManager.GetString("BirthdayReminderWidgetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Content.
        /// </summary>
        public static string BtnAddContent {
            get {
                return ResourceManager.GetString("BtnAddContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize Widgets.
        /// </summary>
        public static string BtnCustomizeWidgets {
            get {
                return ResourceManager.GetString("BtnCustomizeWidgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows your colleagues&apos; recent actions.
        /// </summary>
        public static string CommunityActivityWidgetDescription {
            get {
                return ResourceManager.GetString("CommunityActivityWidgetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s New.
        /// </summary>
        public static string CommunityActivityWidgetName {
            get {
                return ResourceManager.GetString("CommunityActivityWidgetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize Widgets.
        /// </summary>
        public static string CustomizeDashboardLink {
            get {
                return ResourceManager.GetString("CustomizeDashboardLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {!Users}.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to {0}.
        /// </summary>
        public static string GreetingPrefix {
            get {
                return ResourceManager.GetString("GreetingPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows your new users.
        /// </summary>
        public static string NewEmployeeWidgetDescription {
            get {
                return ResourceManager.GetString("NewEmployeeWidgetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New {!Users}.
        /// </summary>
        public static string NewEmployeeWidgetName {
            get {
                return ResourceManager.GetString("NewEmployeeWidgetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View user details, create posts in blogs and forums. Share photos, bookmarks and Wiki pages..
        /// </summary>
        public static string ProductDescription {
            get {
                return ResourceManager.GetString("ProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick action.
        /// </summary>
        public static string QuickActions {
            get {
                return ResourceManager.GetString("QuickActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a blog, adding photos, creating a message.
        /// </summary>
        public static string QuickActionsDescription {
            get {
                return ResourceManager.GetString("QuickActionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Widgets.
        /// </summary>
        public static string WidgetPanelTitle {
            get {
                return ResourceManager.GetString("WidgetPanelTitle", resourceCulture);
            }
        }
    }
}
