//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.UserControls.Bookmarking {
    
    
    public partial class BookmarkingRemoverFromFavouritePopup {
        
        /// <summary>
        /// BookmarkingRemoveFromFavouriteContainer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ASC.Web.Controls.Container BookmarkingRemoveFromFavouriteContainer;
        
        /// <summary>
        /// BookmarkingRemoveFromFavouriteLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ASC.Web.Controls.ActionButton BookmarkingRemoveFromFavouriteLink;
    }
}
