//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserControlsCommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserControlsCommonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.UserControlsCommonResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important.
        /// </summary>
        internal static string ActiionTypeContent {
            get {
                return ResourceManager.GetString("ActiionTypeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string ActionTypAll {
            get {
                return ResourceManager.GetString("ActionTypAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Type.
        /// </summary>
        internal static string ActionType {
            get {
                return ResourceManager.GetString("ActionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary.
        /// </summary>
        internal static string ActionTypeActivity {
            get {
                return ResourceManager.GetString("ActionTypeActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity type.
        /// </summary>
        internal static string ActivityType {
            get {
                return ResourceManager.GetString("ActivityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {!Users}.
        /// </summary>
        internal static string AddEmployees {
            get {
                return ResourceManager.GetString("AddEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Products.
        /// </summary>
        internal static string AllProductsTitle {
            get {
                return ResourceManager.GetString("AllProductsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        internal static string BtnChangeProfile {
            get {
                return ResourceManager.GetString("BtnChangeProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal Settings.
        /// </summary>
        internal static string BtnChangeSettings {
            get {
                return ResourceManager.GetString("BtnChangeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEMO mode.
        /// </summary>
        internal static string DemoUserName {
            get {
                return ResourceManager.GetString("DemoUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncheck all.
        /// </summary>
        internal static string DeselectAllModules {
            get {
                return ResourceManager.GetString("DeselectAllModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This month.
        /// </summary>
        internal static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This week.
        /// </summary>
        internal static string LastWeek {
            get {
                return ResourceManager.GetString("LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This year.
        /// </summary>
        internal static string LastYear {
            get {
                return ResourceManager.GetString("LastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select modules.
        /// </summary>
        internal static string ListModules {
            get {
                return ResourceManager.GetString("ListModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string LogoutButton {
            get {
                return ResourceManager.GetString("LogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting quick link....
        /// </summary>
        internal static string QuickLinkDeletingIsInProgress {
            get {
                return ResourceManager.GetString("QuickLinkDeletingIsInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Quick Link....
        /// </summary>
        internal static string QuickLinkEditIsInProgress {
            get {
                return ResourceManager.GetString("QuickLinkEditIsInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string QuickLinksActionsColumn {
            get {
                return ResourceManager.GetString("QuickLinksActionsColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to top panel.
        /// </summary>
        internal static string QuickLinksAddOnTopPanelColumn {
            get {
                return ResourceManager.GetString("QuickLinksAddOnTopPanelColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the {0} quick link?.
        /// </summary>
        internal static string QuickLinksDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("QuickLinksDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string QuickLinksDeleteLink {
            get {
                return ResourceManager.GetString("QuickLinksDeleteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete quick link.
        /// </summary>
        internal static string QuickLinksDeleteLinkTitle {
            get {
                return ResourceManager.GetString("QuickLinksDeleteLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Quick Link.
        /// </summary>
        internal static string QuickLinksDeletePopupWindowTitle {
            get {
                return ResourceManager.GetString("QuickLinksDeletePopupWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string QuickLinksEditLink {
            get {
                return ResourceManager.GetString("QuickLinksEditLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit quick link.
        /// </summary>
        internal static string QuickLinksEditLinkTitle {
            get {
                return ResourceManager.GetString("QuickLinksEditLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        internal static string QuickLinksModuleColumn {
            get {
                return ResourceManager.GetString("QuickLinksModuleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string QuickLinksNameColumn {
            get {
                return ResourceManager.GetString("QuickLinksNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check all.
        /// </summary>
        internal static string SelectAllModules {
            get {
                return ResourceManager.GetString("SelectAllModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed in as.
        /// </summary>
        internal static string SignInAsTitle {
            get {
                return ResourceManager.GetString("SignInAsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select time period.
        /// </summary>
        internal static string TimePeriod {
            get {
                return ResourceManager.GetString("TimePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        internal static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
