using System;
using System.Collections.Generic;

namespace ASC.Projects.Core.Domain.Reports
{
    public class ReportTemplate
    {
        public int Id
        {
            get;
            internal set;
        }

        public string Name
        {
            get;
            set;
        }

        public ReportType ReportType
        {
            get;
            private set;
        }

        public ReportFilter Filter
        {
            get;
            set;
        }

        public string Cron
        {
            get;
            set;
        }

        public string CreateBy
        {
            get;
            set;
        }

        public DateTime CreateOn
        {
            get;
            set;
        }

        public bool AutoGenerated
        {
            get;
            set;
        }

        public int Tenant
        {
            get;
            internal set;
        }

        
        public ReportTemplate(ReportType reportType)
        {
            ReportType = reportType;
            AutoGenerated = false;
        }

        public override string ToString()
        {
            return Name.ToString();
        }

        public override bool Equals(object obj)
        {
            var t = obj as ReportTemplate;
            return t != null && Id.Equals(t.Id);
        }

        public override int GetHashCode()
        {
            return Id.GetHashCode();
        }
    }
}
